.github/workflows/test.yaml
package-lock.json
package.json
tsconfig.json

4 pr merge할 때 jest 테스트 코드 통과 여부 확인하게 하기

---

.eslintrc.json

#12
- require-default-props rule 비활성화

config: require-default-props 옵션 비활성화

---

package-lock.json
package.json

#36 MSW library 설치

---

src/components/public/icon/dynamicIcon/Checkbox.tsx
src/components/public/icon/dynamicIcon/Heart.tsx
src/components/public/icon/dynamicIcon/Save.tsx
src/components/public/icon/dynamicIcon/Sort.tsx
src/components/public/icon/staticIcon/Alarm.tsx
src/components/public/icon/staticIcon/ArrowRight.tsx
src/components/public/icon/staticIcon/Bye.tsx
src/components/public/icon/staticIcon/Check.tsx
src/components/public/icon/staticIcon/Dalaemfit.tsx
src/components/public/icon/staticIcon/Edit.tsx
src/components/public/icon/staticIcon/Person.tsx
src/components/public/icon/staticIcon/VisibilityOff.tsx
src/components/public/icon/staticIcon/VisibilityOn.tsx
src/components/public/icon/staticIcon/Workation.tsx
src/components/public/icon/staticIcon/X.tsx
src/components/public/img/Edit.tsx
src/components/public/img/Head.tsx
src/components/public/img/ImgLogin.tsx
src/components/public/img/Logo.tsx
src/components/public/img/Profile.tsx
src/components/public/img/ProfileBG.tsx

> ex) #42
> icon, img 컴포넌트에서 파일을 불러오는 경로가 잘못된 것을 수정했습니다.
>

#42 icon, img 파일 불러오는 경로 수정

---

src/components/public/button/Button.test.tsx
src/components/public/button/Button.tsx

> ex) #38
> - [x] 버튼 컴포넌트 작성
> - [x] 버튼 컴포넌트 테스트 코드 작성
> 버튼 컴포넌트는 클라이언트 컴포넌트로 작성되었습니다.
사용 가능한 props는 `className, borderStyle, size, disabled, children, onClick` 이 있습니다.
> className을 통해 tailwind 스타일을 추가할  수 있으며 borderStyle, size를 통해 스타일을 변경할 수 있습니다.
예) className으로 w-full을 주면 기존 사이즈가 덮어씌워집니다.
※ disabled prop이 전달되면 다른 props와 관계없이 버튼이 disabled가 됩니다.(스타일도 자동 변경)
그리고 onClick을 통해 버튼 클릭 동작을 전달할 수 있습니다.
hover, active 이벤트 발생 시 자동으로 스타일이 변합니다
>
> 딱히 없습니다

#38 button 컴포넌트 추가

---

src/components/public/button/Button.test.tsx
src/components/public/button/Button.tsx

- size props 제거
- 일반적인 padding값 baseStyles에 추가
> ex) #이슈번호, #이슈번호
>

refactor: button 컴포넌트 props에서 size 제거

---

.github/workflows/test.yaml

> #49
> build시에 env URL을 전달을 위해 test.YAML을 수정합니다.

 #49 yaml 파일 수정

---

src/app/wishlist/List.tsx
src/app/wishlist/page.tsx
src/app/wishlist/wishlist.test.tsx
src/components/app/provider.tsx
src/components/app/queryClient.ts

> #39 
> React-Query Provdier 설정값을 변경하고 찜한 모임 레이아웃을 구성했습니다.
일단 React-Query Provider 작성한곳 바로 옆에 분리해서 뒀는데 폴더는 따로 만드는게 좋을까요?

#39 찜한 모임 페이지 레이아웃

---

src/components/public/input/InputField.test.tsx
src/components/public/input/InputField.tsx
src/components/public/input/components/Dropdown.tsx

> ex) #65
> InputField에 name prop 추가
>

#65: name prop 추가

---

src/actions/fetchMyPageInfo.ts
src/app/(myPage)/mypage/page.tsx
src/components/pages/mypage/MyPageInfoTap.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/public/Card/Card.tsx

> #74 
- <Suspense> 사용을 위해 `useQuery`에서 `useSuspenseQuery`로 전환
<br />
- fallback으로 `<Spinner />` 컴포넌트 사용
- 데이터 바인딩 확인
<br />
<br />
- 컴포넌트 렌더링시 필요한 컴포넌트 css 수정
<br />
<br />
<br />
- card 컴포넌트에서 내가 만든 모임일 경우 버튼 렌더링 안되도록 수정 부탁드립니다. Props는 `isMyMeeting boolean`으로 전달하겠습니다. 
<br />
<br />
- 이용 완료로 렌더링 되었고 사용자가 리뷰를 작성한 경우 버튼 텍스트가 내가 쓴 리뷰 보기로 텍스트 수정되도록 수정 부탁드립니다.

#74 마이페이지 info 컴포넌트 data fetching 관련 동작 추가

---

src/middleware.ts

> #81 
> 로그인후에 접속되어야 하는 페이지, 로그인 전에 접속해야 되는 페이지를 middleware을 통해 한번에 관리 하였습니다.
로그인후 접속 가능
/mypage
/wishlist
로그인전 접속 가능
/auth?mode=signin
/auth?mode=signup

feat : Add Middleware

---

src/app/auth/@signin/SigninForm.tsx
src/app/auth/@signup/SignupForm.tsx
src/components/public/button/Button.test.tsx
src/components/public/button/Button.tsx
src/components/public/gnb/GNB.tsx
src/components/public/gnb/components/ProfileComponent.tsx
src/components/public/input/InputField.tsx

> ex) #85
> - [x] 로그인, 회원가입 form에서 1초동안 입력을 하지 않으면 validation 오류가 뜨는 기능 추가
> - [x] 그에 맞게 inputField에서 onFocus 이벤트를 옵셔널 체이닝으로 전달할 수 있게 수정
> - [x] 로그인 요청 시 페이지 이동 전에  0.1초 딜레이를 추가
> - [x] 버튼 컴포넌트에서 중복된 스타일 제거
> - [x] 버튼 컴포넌트에서  hover scale 애니메이션 추가
> - [x] GNB의 요소들에 hover sclae 애니메이션 추가
>
> 버튼 애니메이션이 별로라서 수정하고 싶거나, 버튼 애니메이션을 끄고 킬 수 있는 props가 필요하면 말해주세요

#85 리팩토링 및 애니메이션 추가

---

next.config.mjs
src/actions/addReview.ts
src/actions/apis/Auths.ts
src/actions/editProfileInfo.ts
src/actions/fetchMyPageInfo.ts
src/actions/generateMeetUp.ts
src/actions/getUserInfo.ts
src/actions/onLogout.ts
src/app/(myPage)/mypage/@addReview/(.)addReview/page.tsx
src/app/(myPage)/mypage/@addReview/default.tsx
src/app/(myPage)/mypage/layout.tsx
src/components/pages/mypage/MyPageInfoTap.tsx
src/components/pages/mypage/MyPageInfoTapButton.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/public/Review/ReviewHeartBtn/ReviewHeartBtn.tsx
src/components/public/modal/ReviewModal.tsx

> #79 
<br />
- useSuspenseQuery 에러 수정
- useQuery로 전환
- isLoading 프로퍼티 사용
<br />
<br />
- intercepting router로 review 생성 모달 구현
<br />
<br />
- heart icon 컴포넌트 연결
- 리뷰 등록 api 연결
<br />
<br />
- 테스트 완료
>
- react-hook-form 문제로 mutate로 전환하지 못했습니다. 다음 pr때 전환하겠습니다.
- 유저로그인 관련 cookies확인 기능도 다음 pr때 추가하겠습니다.

#79 리뷰 생성 모달 구현 및 모달 api 연동

---

src/actions/editProfileInfo.ts
src/actions/fetchMyPageInfo.ts
src/app/(myPage)/mypage/@addReview/(.)addReview/page.tsx
src/app/(myPage)/mypage/@edit/(.)edit/page.tsx
src/app/(myPage)/mypage/layout.tsx
src/app/layout.tsx
src/components/app/provider.tsx
src/components/pages/mypage/MyPageInfoTap.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/pages/mypage/ReviewStateButton.tsx
src/components/public/Card/Card.tsx
src/components/public/Card/CardReview.tsx
src/components/public/ProfileBox.tsx
src/components/public/modal/ProfileEditModal.tsx
src/components/public/modal/ReviewModal.tsx
tailwind.config.ts

> ex) #99 
- 리뷰 조건부 조회 로직 추가
- 리뷰 자세히 보기 이동 로직 추가
- mutation()으로 코드 migration
- layout 버그 해결
- profile 수정 이미지 버그 해결
- pofile 이미지 용량 제한 로직 추가
- event bubbling 버그 수정
<br />
<br />
<br />
프로필 수정 확인
<br />
<br />
뮤테이션 동작 확인
<br />
<br />
리뷰 동작 확인
<br />
<br />
유효성 검사
<br />
>
- 무한 스크롤은 다음 작업시 업데이트 하겠습니다.
- react-hook-form의 경우 중요하지 않은 내용일 경우 제외하였습니다.

#99 리뷰 조회 컴포넌트 refactoring

---

src/components/public/Toast.tsx

> ex) #105 
> toast UI가 등장했다가 사라졌을때 replace를 이용하셔 alert가 들어간 searchParameter를 제거 해줍니다.

feat : replace 추가

---

src/app/findMeeting/page.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
src/hooks/useMeetingDetail.tsx
src/types/meeting/meeting.ts

#111 
- 무한 스크롤 구현
- queryKey id값 배열에 넣도록 롤백

모임 찾기 리스트 무한스크롤 구현

---

src/actions/api-hooks/getMeetingDetail.ts
src/app/findMeeting/[slug]/page.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx

#115 만료모임 스타일 적용 + refetch 이슈로 cache no-store 적용

---

src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
src/components/pages/findMeeting/FilterSort/FilterSort.tsx
src/components/public/Filter/Filter.tsx
src/components/public/gnb/components/ProfileComponent.tsx

> ex) #118
> 필터 모달에 useOutsideClick 훅 적용
gnb 확대 sclae 크기 조절 125 => 110
>

#118 디자인 디테일 수정

---

src/app/(myPage)/mypage/@edit/(.)edit/page.tsx
src/components/pages/findMeeting/FilterCalendar/FilterCalendar.tsx
src/components/pages/findMeeting/FilterSort/FilterSort.tsx
src/components/pages/mypage/MyPageInfoTapButton.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/pages/mypage/ReviewStateButton.tsx
src/components/public/Filter/Filter.tsx
src/components/public/modal/ProfileEditModal.tsx
src/components/public/modal/ReviewModal.tsx

>  #119 
버그 수정
- 나의 모임 분류버튼 팝업 가려짐 버그 수정
- default text 추가
- 나의 리뷰 버튼 동작 버그 수정
- modal layout 이탈 버그 수정
<br />
<br />

#119 통합 테스트시 발견한 버그 수정

---

src/components/pages/allReview/List.tsx
src/components/pages/wishlist/ByeBtn.tsx
src/components/pages/wishlist/List.tsx
src/hooks/useWishList.tsx

> #115 
> 찜목록의 코드를 리펙터링하고 리뷰와 찜목록 클릭시 상세정보로 넘어가게 수정하였습니다.

 refactor : 찜모임 use wish list 리팩토링

---

src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/mypage/MyPageDefault.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx

> #129 
<br />
- 업데이트 버그 해결
<br />
- 스켈레톤 ui 전환
>
- Card 컴포넌트에 Link 포함될 예정이므로 삭제하였습니다. 확인부탁드립니다!

#129 마이페이지 업데이트 버그 수정 및 UI 업데이트

---

.eslintignore
.eslintrc.json
cypress.config.ts
cypress/e2e/gnb.cy.ts
cypress/e2e/home.cy.ts
cypress/support/commands.ts
cypress/support/e2e.ts
package-lock.json
package.json
src/actions/editProfileInfo.ts
src/actions/postSigninFn.ts
src/actions/postSignupFn.ts
src/actions/setCookies.ts
src/app/not-found.tsx
src/components/pages/allReview/List.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/pages/wishlist/List.tsx
src/components/public/ProfileEditBtn.tsx
src/components/public/gnb/GNB.test.tsx
src/hooks/usePostSignin.tsx
src/hooks/usePostSignup.ts
src/middleware.ts
tsconfig.json

> ex) #128
> - [x] ROUTE 상수를 사용하지 않은 부분을 사용하도록 수정
> - [x] SigninForm과 SignupForm 컴포넌트의 api response를 더 자세한 타입으로 선언함
>
> ex) signinForm, postSigninFn, SignupForm, postSignupFn 위주로 봐주세요

#128 라우트 상수 수정 및 api 에러 처리 로직 리팩토링

---

src/app/(myPage)/mypage/layout.tsx
src/app/layout.tsx
src/components/pages/mypage/MyPageInfoTapButton.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/pages/mypage/ReviewStateButton.tsx
src/components/pages/wishlist/ByeBtn.tsx
src/components/pages/wishlist/List.tsx
src/components/pages/wishlist/WishBtn.tsx
src/components/public/ProfileBox.tsx
src/components/public/gnb/GNB.tsx
src/components/public/gnb/components/ProfileComponent.tsx
src/hooks/useWishList.tsx
src/provider/CountProvider.tsx

> #134 
- 쿠키 만료시 mypage item 목록 업데이트 렌더링 버그 해결
- 마이페이지 글 padding 미적용 버그 해결
- 버튼 줄바뀜현상 해결
- GNB 찜목록 업데이트 버그 해결
>
- 색은 후에 업데이트 부탁드립니다.

#134 레이아웃 버그 수정

---

cypress/e2e/logIn.cy.ts

> ex) #136 
- input태그 별 에러메세지 테스트
- 로그인 테스트
- 회원가입 테스트
- 버튼 비활성화 및 활성화 전환 테스트

#136 로그인 페이지 테스트 코드 작성

---

src/components/pages/mypage/MyPageDefault.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx

#141 card 컴포넌트 수정

---

src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx

> #143 
> 상세페이지 하단 네비게이션 피그마와 디자인이 다른 점 수정 및 반응형 처리 안되어있어서 수정하였습니다.
또한 네비게이션의 height값이 변동 될경우 몇몇 리뷰가 가려지는 현상이 있어
resize 이벤트를 통해 paddingBottom을 네비게이션 높이값 만큼 자동으로 주어지게 수정하였습니다.

feat : resize될때마다 padding 변경

---

.github/workflows/dispatch.yaml
.github/workflows/trigger-dispatch.yaml

chore: yaml 파일 추가

---

src/components/pages/allReview/Scores/Scores.tsx
src/components/public/modal/ReviewModal.tsx
src/hooks/Review/useScoreCalculation.tsx

> #162 
- 소수점 처리 코드 추가
- useEffect 내의 setTimeout clean-up 기능 추가

#162 리뷰 생성 및 별점 버그 수정

---

cypress.config.ts
cypress/e2e/logIn.cy.ts
cypress/e2e/wishlist.cy.ts

> #158 
<br />
- 환경변수 설정 추가
- 환경변수 적용
- 로그인 후 쿠키 확인 코드 추가
- 테스트 통과 확인
- 환경변수 dotenv사용해야 불러올 수 있네요ㅎ...

#158 cypress 환경변수 설정 및 적용

---

src/app/(MyPage)/mypage/layout.tsx
src/components/public/modal/ProfileEditModal.tsx
src/components/public/modal/ReviewModal.tsx

> #169 
<br />
- 프로필 수정 모달 이미지 업로드 검사 추가
<br />
<br />
- 리뷰 모달 간격 조정
<br />
<br />
- metadata 추사

#169 모달 버그 수정

---

src/app/(MyPage)/mypage/layout.tsx

> #171 
<br />
- metadata 수정
- 죄송합니다. comment 반영 못 했습니다.

#171 metadata 수정

---

cypress/e2e/allReview.cy.ts
src/app/allReview/page.tsx
src/components/pages/allReview/List.tsx
src/components/pages/allReview/Scores/Atoms/RatingBar.tsx
src/components/pages/allReview/Scores/Scores.tsx

> #168 
> 모든 리뷰 페이지의 UI를 수정하고 e2e테스트를 진행 하였습니다.

test : 모든 리뷰 e2e 테스트

---

cypress/e2e/mypage.cy.ts
cypress/support/commands.ts
package-lock.json
package.json

> #165 
- login 함수 생성
- 마이페이지 기본 렌더링 테스트
- 마이페이지 프로필 수정 모달 fail test
- 마이페이지 로그아웃 테스트

#165 마이페이지 e2e 테스트

---

src/app/findMeeting/page.tsx
src/app/wishlist/page.tsx
src/components/pages/findMeeting/MeetingCard/Atoms/ParticipantGage.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/BottomBanner.tsx
src/components/pages/findMeeting/MeetingCard/MeetingDetail/MeetingDetail.tsx
src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
src/components/pages/wishlist/List.tsx

> #174 
> 모임 찾기, 상세, 찜한 모임의 UI를 수정했으며
> 모임 찾기 부분의 마감 기간이 언제 나오는 부분이 적용이 안된것을 확인하고 구현해놨습니다.
24시간 정도 남았을때 "오늘 00시 마감"
24시간 이후 부터는 00일 후 마감
일주일 남았을경우 다음주 마감
이렇게 나오게 수정하였습니다.
상세페이지도 동일하게 수정하였습니다.

feat : 모임 찾기, 상세, 찜한 모임 UI 수정

---

src/actions/Auths/getUserInfo.ts
src/actions/Gatherings/fetchMyPageInfo.ts
src/app/(MyPage)/mypage/@addReview/(.)addReview/page.tsx
src/app/(MyPage)/mypage/@edit/(.)edit/page.tsx
src/app/(MyPage)/mypage/layout.tsx
src/app/(MyPage)/mypage/mypage.d.ts
src/components/pages/mypage/MyPageInfoTap.tsx
src/components/pages/mypage/MyPageInfoTapButton.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/pages/mypage/ReviewStateButton.tsx
src/components/public/img/Profile.tsx
src/components/public/modal/ProfileEditModal.tsx
src/components/public/modal/ReviewModal.tsx
src/types/mypage/mypage.d.ts

> #177 
- 공통 타입은 extend로 상속
- 공통화시 필요한 변수명통합
- 타입을 어디까지 분리하고 정리해야할 지 몰라서 일단 임의로 통합했습니다.

#177 mypage 관련 타입 분리 및 정리

---

public/icon/staticIcon/menuIcon.svg
src/app/layout.tsx
src/components/pages/auth/@signin/SigninForm.tsx
src/components/public/gnb/GNB.tsx
src/components/public/gnb/components/AnimatedMenu.tsx
src/components/public/gnb/components/AnimatedMenuIcon.tsx
src/components/public/gnb/components/ProfileComponent.tsx
src/components/public/icon/staticIcon/MenuIcon.tsx

> ex) #178
> gnb 디자인 수정 및, 처음 로딩 시 조건부 렌더링 에러 문제 수정
https://github.com/user-attachments/assets/68738eb4-a0ac-4a48-b3a7-aba14b2e5f79
>

#178 refactor gnb 디자인 및 디테일 에러 수정

---

src/components/public/modal/ProfileEditModal.tsx

> #187 
- 폼 제출 시 유효성 검증 로직 추가
>

#187 폼 제출 시 유효성 검증 로직 추가

---

src/app/(MyPage)/mypage/page.tsx
src/components/pages/findMeeting/CreateMeeting/CreateMeetingForm.tsx
src/components/pages/mypage/MyPageInfoWrapper.tsx
src/components/public/Card/Card.tsx

> #193 
- 모임 생성 및 삭제 시 마이페이지 미반영 버그 수정
- staleTime 및 gcTime 조정
- 관련 캐시 모두 무효화

#193 모임생성 및 삭제 관련 마이페이지 반영 불가 버그

---

src/components/public/modal/ProfileEditModal.tsx
src/components/public/modal/ReviewModal.tsx

> #191 
- 프로필 및 리뷰 모달 Pop-up animation 추가
>
- 모달인데 과한 애니메이션은 오히려 불필요하다 생각해 적당히 넣었습니다.

191 모달 창 에니메이션 추가

---

src/actions/Reviews/addReview.ts
src/components/public/modal/ReviewModal.tsx
src/types/mypage/mypage.d.ts

> #205 
- 유틸리티 함수 사용
- superset 타입 생성
- score및 gatheringId 타입 통합

#205 mypage 타입 정리

---

src/app/(MyPage)/mypage/page.tsx
src/components/pages/mypage/MyPageInfoTap.tsx
src/hooks/mypage/myPageQuery.ts
src/hooks/mypage/useTapHook.ts

> #207 
- useClient 관련 코드 useHook으로 분리
- prefetch option 수정
>

#207 mypage 코드 관련 파일 분리

---

package-lock.json
package.json
src/app/page.tsx
src/components/pages/findMeeting/MeetingCard/MeetingList/MeetingList.tsx
src/components/pages/mainpage/MainReview.tsx
src/components/pages/mainpage/NewMeeting.tsx
src/components/public/Toast.tsx
src/components/public/bottomFloatingBar/BottomFloatingBar.tsx
src/components/public/gnb/components/SideBarMenu.tsx

> ex) #198
> 메인 페이지에 틀어지는 부분 수정
> 메인 페이지 모임 불러오는 fraction 오류 수정
> toast ui 디자인 변경 및 기능 수정
> 및 각종 디테일 수정

feat :  UI 디테일

---

cypress/e2e/allReview.cy.ts
cypress/e2e/gnb.cy.ts
cypress/e2e/home.cy.ts
cypress/e2e/mypage.cy.ts
cypress/e2e/signup.cy.ts
cypress/e2e/wishlist.cy.ts

> #211 
<br />
<br />
<br />
<br />
<br />
<br />
<br />
- elem 선택 코드 수정
- 로그인 로직 수정으로 api 보호
- cypress terminal 실행 시에도 오류 미발생 확인
>

#211 ui 및 refactoring 에 따른 test code 수정

---

cypress/e2e/gnb.cy.ts

> #211 
- gnb 수정에 따른 test 코드 수정

#211 gnb 수정에 따른 test 코드 수정

---

src/app/page.tsx
src/constants/limit.ts

hotfix: 기본 상수 수정
